---
- name: ensure cookies are the same between all envs
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie

- name: get server hostnames in cluster
  set_fact:
    nodes: "{{ lookup('find_by_tag', 'key=Name value=rabbitmq').split(',') }}"
