---
- name: ensure cookies are the same between all envs
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie

- name: change hostname
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf

- name: get server hostnames in cluster
  ec2_search:
    key: "{{ rabbitmq_ec2_tag_key }}"
    value: "{{ rabbitmq_ec2_tag_value }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ app_settings['rabbitmq']['aws_access_key_id'] }}"
    AWS_SECRET_ACCESS_KEY: "{{ app_settings['rabbitmq']['aws_secret_access_key'] }}"
  register: nodes

- name: start rabbitmq-server (clustering)
  service:
    name: rabbitmq-server
    state: started

- name: turn off rabbitmq but not the erlang process
  command: "{{ item }}"
  with_items:
    - rabbitmqctl stop_app
    - rabbitmqctl reset

- name: cluster all known nodes
  command: "rabbitmqctl join_cluster rabbit@{{item['hostname']}}.ec2.internal"
  with_items: "{{ nodes['info']|default([]) }}"
  when: nodes
  ignore_errors: yes

- name: turn back on rabbitmq
  command: rabbitmqctl start_app

- name: stop rabbitmq-server (clustering)
  service:
    name: rabbitmq-server
    state: stopped
