---
# tasks file for rabbitmq
- name: add rabbitmq key (Debian)
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present
  when: ansible_os_family == 'Debian'

- name: add rabbitmq repo (Debian)
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present update_cache=yes
  when: ansible_os_family == 'Debian'

- name: install packages
  apt:
    name: rabbitmq-server
    state: present
  when: ansible_os_family == 'Debian'

- name: ensure cookies are the same between all envs
  template: src=erlang.cookie.j2 dest=/var/lib/rabbitmq/.erlang.cookie

- name: configure rabbitmq-server
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq-server

- name: enable management plugin
  command: rabbitmq-plugins enable rabbitmq_management
  when: rabbitmq-manage

- name: Setup rabbitmq user with admin access
  command: "rabbitmqctl {{ item.key }} {{ item }}"
  with_items:
    - rabbitmqctl add_user {{ rabbitmq_default_user }} {{ rabbitmq_default_pass }}
    - rabbitmqctl set_user_tags {{ rabbitmq_default_user }} {{ rabbitmq_default_user_tags }}
    - rabbitmqctl set_permissions -p {{ rabbitmq_default_vhost }} {{ rabbitmq_default_user }} ".*" ".*" ".*"
  when: make-super-user
